# Generated by Django 5.0.3 on 2026-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload banner image', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload category icon', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL (or upload file below)', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_image',
            field=models.CharField(blank=True, help_text='Image URL (or upload file below)', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL (or upload file below)', max_length=500),
        ),
    ]
